### ISSUE TITLE
Error in get_light_objects

### ISSUE THREAD

**Issue by cchaz003** [studioimaginaire/phue#29]
Whenever I try to run the get_light_objects method I get the following error:

```
Traceback (most recent call last):
  File "random_colors.py", line 14, in <module>
    lights = b.get_light_objects()
  File "/Users/abcd/abcd/Hue/Python/examples/phue.py", line 562, in get_light_objects
    self.lights_by_id[int(light)] = Light(self, int(light))
TypeError: int() argument must be a string or a number, not 'dict'
```

The error started appearing for me about 2 or 3 weeks ago. I noticed it after a base station update (maybe the problem?) but I dont think there was an API change. I dont think its my code either since I get this error while running the examples as well (the error above came from the "random_colors.py" example).

Any idea why this started happening?

**Comment by alexfromapex** [comment]
Having this same issue, after not running my script for a long time

**Comment by natcl** [comment]
Perhaps your API key isn't valid anymore. Try deleting the .python_hue file and doing the registration/button push again

**Comment by alexfromapex** [comment]
That worked, thanks! I just had to push the button again.  Otherwise, I got this error:

`Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    b = phue.Bridge('192.168.1.76')
  File "C:\Python27\lib\site-packages\phue.py", line 427, in __init__
    self.connect()
  File "C:\Python27\lib\site-packages\phue.py", line 551, in connect
    self.register_app()
  File "C:\Python27\lib\site-packages\phue.py", line 519, in register_app
    'The link button has not been pressed in the last 30 seconds.')
PhueRegistrationException`
